# Generated by Django 6.0.6 on 2026-06-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='city',
            field=models.CharField(blank=True, default='Nepal', max_length=100),
        ),
        migrations.AddField(
            model_name='photographer',
            name='price_per_shoot',
            field=models.PositiveIntegerField(default=0, help_text='Price in Nepalese Rupees'),
        ),
        migrations.AddField(
            model_name='photographer',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=2),
        ),
        migrations.AddField(
            model_name='photographer',
            name='specialty',
            field=models.CharField(choices=[('Wedding', 'Wedding'), ('Portrait', 'Portrait'), ('Family', 'Family'), ('Fashion', 'Fashion'), ('Travel', 'Travel')], default='Portrait', max_length=20),
        ),
        migrations.AddField(
            model_name='photographer',
            name='years_experience',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
