# Generated by Django 6.0.6 on 2026-06-28 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_photographer_city_photographer_price_per_shoot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='photographer',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='photographer',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='photographer',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='photographer',
            name='profile_image',
            field=models.FileField(blank=True, upload_to='photographers/profiles/'),
        ),
        migrations.CreateModel(
            name='PhotographerProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('completed_at', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.FileField(blank=True, upload_to='photographers/projects/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='accounts.photographer')),
            ],
            options={
                'ordering': ['-completed_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='photographers/portfolio/')),
                ('caption', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_images', to='accounts.photographer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
