# Generated by Django 6.0.6 on 2026-07-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_savedphotographer'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='citizenship_back',
            field=models.FileField(blank=True, upload_to='photographers/kyc/'),
        ),
        migrations.AddField(
            model_name='photographer',
            name='citizenship_front',
            field=models.FileField(blank=True, upload_to='photographers/kyc/'),
        ),
        migrations.AddField(
            model_name='photographer',
            name='citizenship_number',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='photographer',
            name='kyc_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photographer',
            name='kyc_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='photographer',
            name='kyc_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
