# Generated by Django 6.0.6 on 2026-07-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_photographer_citizenship_back_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='citizenship_number',
            field=models.CharField(max_length=40),
        ),
    ]
