# Generated by Django 6.0.6 on 2026-07-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_photographer_citizenship_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='specialty',
            field=models.CharField(default='Portrait', max_length=40),
        ),
    ]
