# Generated by Django 6.0.6 on 2026-06-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('discount_percent', models.PositiveSmallIntegerField(help_text='Discount percentage, e.g. 20 for 20% off')),
                ('description', models.TextField(max_length=300)),
                ('ends_at', models.DateField(help_text='Last day this offer is valid')),
                ('icon', models.CharField(default='fa-tag', help_text='Font Awesome 4 icon class', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['ends_at'],
            },
        ),
    ]
