# Generated by Django 6.0.6 on 2026-06-28 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_savedphotographer'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=120)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_phone', models.CharField(blank=True, max_length=30)),
                ('shoot_date', models.DateField(blank=True, null=True)),
                ('package', models.CharField(choices=[('Essential', 'Essential'), ('Signature', 'Signature'), ('Full Day', 'Full Day'), ('Custom', 'Custom')], default='Custom', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_requests', to='accounts.photographer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
