# Generated by Django 6.0.6 on 2026-07-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bookingrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrequest',
            name='client_phone',
            field=models.CharField(max_length=30),
        ),
    ]
