# Generated by Django 6.0.6 on 2026-07-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_bookingrequest_client_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrequest',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='shoot_date',
            field=models.DateField(),
        ),
    ]
