# Generated by Django 6.0.6 on 2026-07-07 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_photographer_citizenship_back_and_more'),
        ('main', '0004_alter_bookingrequest_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='photographer',
            field=models.ForeignKey(blank=True, help_text='Leave blank for a site-wide offer', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='accounts.photographer'),
        ),
    ]
